// <auto-generated />
using System;
using DCPServiceRepository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DCPServiceRepository.Migrations
{
    [DbContext(typeof(DenormRepoDbContext))]
    [Migration("20181130192110_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DCPServiceRepository.Models.ConfigCallLog", b =>
                {
                    b.Property<Guid>("CallId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ElapsedTime");

                    b.Property<DateTime>("Expirytime");

                    b.Property<DateTime>("FinishTime");

                    b.Property<string>("Key");

                    b.Property<DateTime>("RequestStartTime");

                    b.Property<string>("Status");

                    b.HasKey("CallId");

                    b.ToTable("CallLog");
                });

            modelBuilder.Entity("DCPServiceRepository.Models.OrderCode", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FinishTime");

                    b.Property<string>("Request");

                    b.Property<string>("Response");

                    b.HasKey("Key");

                    b.ToTable("OrderCode");
                });
#pragma warning restore 612, 618
        }
    }
}
